// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_messages.proto

package edu.usfca.cs.dfs;

public final class StorageMessages {
  private StorageMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.DataPacket.packetType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.DataPacket.packetType type = 1;</code>
     */
    edu.usfca.cs.dfs.StorageMessages.DataPacket.packetType getType();

    /**
     * <code>string fileName = 2;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>string fileName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>int32 numChunk = 3;</code>
     */
    int getNumChunk();

    /**
     * <code>int32 chunkId = 4;</code>
     */
    int getChunkId();

    /**
     * <code>bytes data = 5;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>bool is_last = 6;</code>
     */
    boolean getIsLast();

    /**
     * <code>int32 usage = 7;</code>
     */
    int getUsage();

    /**
     * <code>int32 requestNum = 8;</code>
     */
    int getRequestNum();

    /**
     * <code>repeated .NodeHash nodeList = 9;</code>
     */
    java.util.List<edu.usfca.cs.dfs.StorageMessages.NodeHash> 
        getNodeListList();
    /**
     * <code>repeated .NodeHash nodeList = 9;</code>
     */
    edu.usfca.cs.dfs.StorageMessages.NodeHash getNodeList(int index);
    /**
     * <code>repeated .NodeHash nodeList = 9;</code>
     */
    int getNodeListCount();
    /**
     * <code>repeated .NodeHash nodeList = 9;</code>
     */
    java.util.List<? extends edu.usfca.cs.dfs.StorageMessages.NodeHashOrBuilder> 
        getNodeListOrBuilderList();
    /**
     * <code>repeated .NodeHash nodeList = 9;</code>
     */
    edu.usfca.cs.dfs.StorageMessages.NodeHashOrBuilder getNodeListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DataPacket}
   */
  public  static final class DataPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataPacket)
      DataPacketOrBuilder {
    // Use DataPacket.newBuilder() to construct.
    private DataPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataPacket() {
      type_ = 0;
      fileName_ = "";
      numChunk_ = 0;
      chunkId_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      isLast_ = false;
      usage_ = 0;
      requestNum_ = 0;
      nodeList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DataPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 24: {

              numChunk_ = input.readInt32();
              break;
            }
            case 32: {

              chunkId_ = input.readInt32();
              break;
            }
            case 42: {

              data_ = input.readBytes();
              break;
            }
            case 48: {

              isLast_ = input.readBool();
              break;
            }
            case 56: {

              usage_ = input.readInt32();
              break;
            }
            case 64: {

              requestNum_ = input.readInt32();
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                nodeList_ = new java.util.ArrayList<edu.usfca.cs.dfs.StorageMessages.NodeHash>();
                mutable_bitField0_ |= 0x00000100;
              }
              nodeList_.add(
                  input.readMessage(edu.usfca.cs.dfs.StorageMessages.NodeHash.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          nodeList_ = java.util.Collections.unmodifiableList(nodeList_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_DataPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_DataPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.StorageMessages.DataPacket.class, edu.usfca.cs.dfs.StorageMessages.DataPacket.Builder.class);
    }

    /**
     * Protobuf enum {@code DataPacket.packetType}
     */
    public enum packetType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REQUEST = 0;</code>
       */
      REQUEST(0),
      /**
       * <code>ACK = 1;</code>
       */
      ACK(1),
      /**
       * <code>DATA = 2;</code>
       */
      DATA(2),
      /**
       * <code>HEARTBEAT = 3;</code>
       */
      HEARTBEAT(3),
      /**
       * <code>NODELIST = 4;</code>
       */
      NODELIST(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>REQUEST = 0;</code>
       */
      public static final int REQUEST_VALUE = 0;
      /**
       * <code>ACK = 1;</code>
       */
      public static final int ACK_VALUE = 1;
      /**
       * <code>DATA = 2;</code>
       */
      public static final int DATA_VALUE = 2;
      /**
       * <code>HEARTBEAT = 3;</code>
       */
      public static final int HEARTBEAT_VALUE = 3;
      /**
       * <code>NODELIST = 4;</code>
       */
      public static final int NODELIST_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static packetType valueOf(int value) {
        return forNumber(value);
      }

      public static packetType forNumber(int value) {
        switch (value) {
          case 0: return REQUEST;
          case 1: return ACK;
          case 2: return DATA;
          case 3: return HEARTBEAT;
          case 4: return NODELIST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<packetType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          packetType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<packetType>() {
              public packetType findValueByNumber(int number) {
                return packetType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.StorageMessages.DataPacket.getDescriptor().getEnumTypes().get(0);
      }

      private static final packetType[] VALUES = values();

      public static packetType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private packetType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DataPacket.packetType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.DataPacket.packetType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.DataPacket.packetType type = 1;</code>
     */
    public edu.usfca.cs.dfs.StorageMessages.DataPacket.packetType getType() {
      edu.usfca.cs.dfs.StorageMessages.DataPacket.packetType result = edu.usfca.cs.dfs.StorageMessages.DataPacket.packetType.valueOf(type_);
      return result == null ? edu.usfca.cs.dfs.StorageMessages.DataPacket.packetType.UNRECOGNIZED : result;
    }

    public static final int FILENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string fileName = 2;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMCHUNK_FIELD_NUMBER = 3;
    private int numChunk_;
    /**
     * <code>int32 numChunk = 3;</code>
     */
    public int getNumChunk() {
      return numChunk_;
    }

    public static final int CHUNKID_FIELD_NUMBER = 4;
    private int chunkId_;
    /**
     * <code>int32 chunkId = 4;</code>
     */
    public int getChunkId() {
      return chunkId_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 5;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int IS_LAST_FIELD_NUMBER = 6;
    private boolean isLast_;
    /**
     * <code>bool is_last = 6;</code>
     */
    public boolean getIsLast() {
      return isLast_;
    }

    public static final int USAGE_FIELD_NUMBER = 7;
    private int usage_;
    /**
     * <code>int32 usage = 7;</code>
     */
    public int getUsage() {
      return usage_;
    }

    public static final int REQUESTNUM_FIELD_NUMBER = 8;
    private int requestNum_;
    /**
     * <code>int32 requestNum = 8;</code>
     */
    public int getRequestNum() {
      return requestNum_;
    }

    public static final int NODELIST_FIELD_NUMBER = 9;
    private java.util.List<edu.usfca.cs.dfs.StorageMessages.NodeHash> nodeList_;
    /**
     * <code>repeated .NodeHash nodeList = 9;</code>
     */
    public java.util.List<edu.usfca.cs.dfs.StorageMessages.NodeHash> getNodeListList() {
      return nodeList_;
    }
    /**
     * <code>repeated .NodeHash nodeList = 9;</code>
     */
    public java.util.List<? extends edu.usfca.cs.dfs.StorageMessages.NodeHashOrBuilder> 
        getNodeListOrBuilderList() {
      return nodeList_;
    }
    /**
     * <code>repeated .NodeHash nodeList = 9;</code>
     */
    public int getNodeListCount() {
      return nodeList_.size();
    }
    /**
     * <code>repeated .NodeHash nodeList = 9;</code>
     */
    public edu.usfca.cs.dfs.StorageMessages.NodeHash getNodeList(int index) {
      return nodeList_.get(index);
    }
    /**
     * <code>repeated .NodeHash nodeList = 9;</code>
     */
    public edu.usfca.cs.dfs.StorageMessages.NodeHashOrBuilder getNodeListOrBuilder(
        int index) {
      return nodeList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != edu.usfca.cs.dfs.StorageMessages.DataPacket.packetType.REQUEST.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileName_);
      }
      if (numChunk_ != 0) {
        output.writeInt32(3, numChunk_);
      }
      if (chunkId_ != 0) {
        output.writeInt32(4, chunkId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(5, data_);
      }
      if (isLast_ != false) {
        output.writeBool(6, isLast_);
      }
      if (usage_ != 0) {
        output.writeInt32(7, usage_);
      }
      if (requestNum_ != 0) {
        output.writeInt32(8, requestNum_);
      }
      for (int i = 0; i < nodeList_.size(); i++) {
        output.writeMessage(9, nodeList_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != edu.usfca.cs.dfs.StorageMessages.DataPacket.packetType.REQUEST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileName_);
      }
      if (numChunk_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, numChunk_);
      }
      if (chunkId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, chunkId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      if (isLast_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isLast_);
      }
      if (usage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, usage_);
      }
      if (requestNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, requestNum_);
      }
      for (int i = 0; i < nodeList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, nodeList_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.StorageMessages.DataPacket)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.StorageMessages.DataPacket other = (edu.usfca.cs.dfs.StorageMessages.DataPacket) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getFileName()
          .equals(other.getFileName());
      result = result && (getNumChunk()
          == other.getNumChunk());
      result = result && (getChunkId()
          == other.getChunkId());
      result = result && getData()
          .equals(other.getData());
      result = result && (getIsLast()
          == other.getIsLast());
      result = result && (getUsage()
          == other.getUsage());
      result = result && (getRequestNum()
          == other.getRequestNum());
      result = result && getNodeListList()
          .equals(other.getNodeListList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + NUMCHUNK_FIELD_NUMBER;
      hash = (53 * hash) + getNumChunk();
      hash = (37 * hash) + CHUNKID_FIELD_NUMBER;
      hash = (53 * hash) + getChunkId();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + IS_LAST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLast());
      hash = (37 * hash) + USAGE_FIELD_NUMBER;
      hash = (53 * hash) + getUsage();
      hash = (37 * hash) + REQUESTNUM_FIELD_NUMBER;
      hash = (53 * hash) + getRequestNum();
      if (getNodeListCount() > 0) {
        hash = (37 * hash) + NODELIST_FIELD_NUMBER;
        hash = (53 * hash) + getNodeListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.StorageMessages.DataPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.DataPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.DataPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.DataPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.DataPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.DataPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.DataPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.DataPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.DataPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.DataPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.DataPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.DataPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.StorageMessages.DataPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataPacket)
        edu.usfca.cs.dfs.StorageMessages.DataPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_DataPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_DataPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.StorageMessages.DataPacket.class, edu.usfca.cs.dfs.StorageMessages.DataPacket.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.StorageMessages.DataPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodeListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        fileName_ = "";

        numChunk_ = 0;

        chunkId_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        isLast_ = false;

        usage_ = 0;

        requestNum_ = 0;

        if (nodeListBuilder_ == null) {
          nodeList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          nodeListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_DataPacket_descriptor;
      }

      public edu.usfca.cs.dfs.StorageMessages.DataPacket getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.StorageMessages.DataPacket.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.StorageMessages.DataPacket build() {
        edu.usfca.cs.dfs.StorageMessages.DataPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.StorageMessages.DataPacket buildPartial() {
        edu.usfca.cs.dfs.StorageMessages.DataPacket result = new edu.usfca.cs.dfs.StorageMessages.DataPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.fileName_ = fileName_;
        result.numChunk_ = numChunk_;
        result.chunkId_ = chunkId_;
        result.data_ = data_;
        result.isLast_ = isLast_;
        result.usage_ = usage_;
        result.requestNum_ = requestNum_;
        if (nodeListBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            nodeList_ = java.util.Collections.unmodifiableList(nodeList_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.nodeList_ = nodeList_;
        } else {
          result.nodeList_ = nodeListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.StorageMessages.DataPacket) {
          return mergeFrom((edu.usfca.cs.dfs.StorageMessages.DataPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.StorageMessages.DataPacket other) {
        if (other == edu.usfca.cs.dfs.StorageMessages.DataPacket.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.getNumChunk() != 0) {
          setNumChunk(other.getNumChunk());
        }
        if (other.getChunkId() != 0) {
          setChunkId(other.getChunkId());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getIsLast() != false) {
          setIsLast(other.getIsLast());
        }
        if (other.getUsage() != 0) {
          setUsage(other.getUsage());
        }
        if (other.getRequestNum() != 0) {
          setRequestNum(other.getRequestNum());
        }
        if (nodeListBuilder_ == null) {
          if (!other.nodeList_.isEmpty()) {
            if (nodeList_.isEmpty()) {
              nodeList_ = other.nodeList_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureNodeListIsMutable();
              nodeList_.addAll(other.nodeList_);
            }
            onChanged();
          }
        } else {
          if (!other.nodeList_.isEmpty()) {
            if (nodeListBuilder_.isEmpty()) {
              nodeListBuilder_.dispose();
              nodeListBuilder_ = null;
              nodeList_ = other.nodeList_;
              bitField0_ = (bitField0_ & ~0x00000100);
              nodeListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodeListFieldBuilder() : null;
            } else {
              nodeListBuilder_.addAllMessages(other.nodeList_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.StorageMessages.DataPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.StorageMessages.DataPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.DataPacket.packetType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.DataPacket.packetType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.DataPacket.packetType type = 1;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.DataPacket.packetType getType() {
        edu.usfca.cs.dfs.StorageMessages.DataPacket.packetType result = edu.usfca.cs.dfs.StorageMessages.DataPacket.packetType.valueOf(type_);
        return result == null ? edu.usfca.cs.dfs.StorageMessages.DataPacket.packetType.UNRECOGNIZED : result;
      }
      /**
       * <code>.DataPacket.packetType type = 1;</code>
       */
      public Builder setType(edu.usfca.cs.dfs.StorageMessages.DataPacket.packetType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.DataPacket.packetType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string fileName = 2;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 2;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 2;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 2;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private int numChunk_ ;
      /**
       * <code>int32 numChunk = 3;</code>
       */
      public int getNumChunk() {
        return numChunk_;
      }
      /**
       * <code>int32 numChunk = 3;</code>
       */
      public Builder setNumChunk(int value) {
        
        numChunk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numChunk = 3;</code>
       */
      public Builder clearNumChunk() {
        
        numChunk_ = 0;
        onChanged();
        return this;
      }

      private int chunkId_ ;
      /**
       * <code>int32 chunkId = 4;</code>
       */
      public int getChunkId() {
        return chunkId_;
      }
      /**
       * <code>int32 chunkId = 4;</code>
       */
      public Builder setChunkId(int value) {
        
        chunkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chunkId = 4;</code>
       */
      public Builder clearChunkId() {
        
        chunkId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 5;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 5;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 5;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private boolean isLast_ ;
      /**
       * <code>bool is_last = 6;</code>
       */
      public boolean getIsLast() {
        return isLast_;
      }
      /**
       * <code>bool is_last = 6;</code>
       */
      public Builder setIsLast(boolean value) {
        
        isLast_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_last = 6;</code>
       */
      public Builder clearIsLast() {
        
        isLast_ = false;
        onChanged();
        return this;
      }

      private int usage_ ;
      /**
       * <code>int32 usage = 7;</code>
       */
      public int getUsage() {
        return usage_;
      }
      /**
       * <code>int32 usage = 7;</code>
       */
      public Builder setUsage(int value) {
        
        usage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 usage = 7;</code>
       */
      public Builder clearUsage() {
        
        usage_ = 0;
        onChanged();
        return this;
      }

      private int requestNum_ ;
      /**
       * <code>int32 requestNum = 8;</code>
       */
      public int getRequestNum() {
        return requestNum_;
      }
      /**
       * <code>int32 requestNum = 8;</code>
       */
      public Builder setRequestNum(int value) {
        
        requestNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 requestNum = 8;</code>
       */
      public Builder clearRequestNum() {
        
        requestNum_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<edu.usfca.cs.dfs.StorageMessages.NodeHash> nodeList_ =
        java.util.Collections.emptyList();
      private void ensureNodeListIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          nodeList_ = new java.util.ArrayList<edu.usfca.cs.dfs.StorageMessages.NodeHash>(nodeList_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          edu.usfca.cs.dfs.StorageMessages.NodeHash, edu.usfca.cs.dfs.StorageMessages.NodeHash.Builder, edu.usfca.cs.dfs.StorageMessages.NodeHashOrBuilder> nodeListBuilder_;

      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public java.util.List<edu.usfca.cs.dfs.StorageMessages.NodeHash> getNodeListList() {
        if (nodeListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodeList_);
        } else {
          return nodeListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public int getNodeListCount() {
        if (nodeListBuilder_ == null) {
          return nodeList_.size();
        } else {
          return nodeListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.NodeHash getNodeList(int index) {
        if (nodeListBuilder_ == null) {
          return nodeList_.get(index);
        } else {
          return nodeListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public Builder setNodeList(
          int index, edu.usfca.cs.dfs.StorageMessages.NodeHash value) {
        if (nodeListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeListIsMutable();
          nodeList_.set(index, value);
          onChanged();
        } else {
          nodeListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public Builder setNodeList(
          int index, edu.usfca.cs.dfs.StorageMessages.NodeHash.Builder builderForValue) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          nodeList_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodeListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public Builder addNodeList(edu.usfca.cs.dfs.StorageMessages.NodeHash value) {
        if (nodeListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeListIsMutable();
          nodeList_.add(value);
          onChanged();
        } else {
          nodeListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public Builder addNodeList(
          int index, edu.usfca.cs.dfs.StorageMessages.NodeHash value) {
        if (nodeListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeListIsMutable();
          nodeList_.add(index, value);
          onChanged();
        } else {
          nodeListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public Builder addNodeList(
          edu.usfca.cs.dfs.StorageMessages.NodeHash.Builder builderForValue) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          nodeList_.add(builderForValue.build());
          onChanged();
        } else {
          nodeListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public Builder addNodeList(
          int index, edu.usfca.cs.dfs.StorageMessages.NodeHash.Builder builderForValue) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          nodeList_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodeListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public Builder addAllNodeList(
          java.lang.Iterable<? extends edu.usfca.cs.dfs.StorageMessages.NodeHash> values) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodeList_);
          onChanged();
        } else {
          nodeListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public Builder clearNodeList() {
        if (nodeListBuilder_ == null) {
          nodeList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          nodeListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public Builder removeNodeList(int index) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          nodeList_.remove(index);
          onChanged();
        } else {
          nodeListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.NodeHash.Builder getNodeListBuilder(
          int index) {
        return getNodeListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.NodeHashOrBuilder getNodeListOrBuilder(
          int index) {
        if (nodeListBuilder_ == null) {
          return nodeList_.get(index);  } else {
          return nodeListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public java.util.List<? extends edu.usfca.cs.dfs.StorageMessages.NodeHashOrBuilder> 
           getNodeListOrBuilderList() {
        if (nodeListBuilder_ != null) {
          return nodeListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodeList_);
        }
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.NodeHash.Builder addNodeListBuilder() {
        return getNodeListFieldBuilder().addBuilder(
            edu.usfca.cs.dfs.StorageMessages.NodeHash.getDefaultInstance());
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.NodeHash.Builder addNodeListBuilder(
          int index) {
        return getNodeListFieldBuilder().addBuilder(
            index, edu.usfca.cs.dfs.StorageMessages.NodeHash.getDefaultInstance());
      }
      /**
       * <code>repeated .NodeHash nodeList = 9;</code>
       */
      public java.util.List<edu.usfca.cs.dfs.StorageMessages.NodeHash.Builder> 
           getNodeListBuilderList() {
        return getNodeListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          edu.usfca.cs.dfs.StorageMessages.NodeHash, edu.usfca.cs.dfs.StorageMessages.NodeHash.Builder, edu.usfca.cs.dfs.StorageMessages.NodeHashOrBuilder> 
          getNodeListFieldBuilder() {
        if (nodeListBuilder_ == null) {
          nodeListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              edu.usfca.cs.dfs.StorageMessages.NodeHash, edu.usfca.cs.dfs.StorageMessages.NodeHash.Builder, edu.usfca.cs.dfs.StorageMessages.NodeHashOrBuilder>(
                  nodeList_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          nodeList_ = null;
        }
        return nodeListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:DataPacket)
    }

    // @@protoc_insertion_point(class_scope:DataPacket)
    private static final edu.usfca.cs.dfs.StorageMessages.DataPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.StorageMessages.DataPacket();
    }

    public static edu.usfca.cs.dfs.StorageMessages.DataPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataPacket>
        PARSER = new com.google.protobuf.AbstractParser<DataPacket>() {
      public DataPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DataPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataPacket> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.StorageMessages.DataPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NodeHashOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NodeHash)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string hashVal = 1;</code>
     */
    java.lang.String getHashVal();
    /**
     * <code>string hashVal = 1;</code>
     */
    com.google.protobuf.ByteString
        getHashValBytes();

    /**
     * <code>string hostPort = 2;</code>
     */
    java.lang.String getHostPort();
    /**
     * <code>string hostPort = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostPortBytes();
  }
  /**
   * Protobuf type {@code NodeHash}
   */
  public  static final class NodeHash extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NodeHash)
      NodeHashOrBuilder {
    // Use NodeHash.newBuilder() to construct.
    private NodeHash(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodeHash() {
      hashVal_ = "";
      hostPort_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NodeHash(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hashVal_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              hostPort_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_NodeHash_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_NodeHash_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.StorageMessages.NodeHash.class, edu.usfca.cs.dfs.StorageMessages.NodeHash.Builder.class);
    }

    public static final int HASHVAL_FIELD_NUMBER = 1;
    private volatile java.lang.Object hashVal_;
    /**
     * <code>string hashVal = 1;</code>
     */
    public java.lang.String getHashVal() {
      java.lang.Object ref = hashVal_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hashVal_ = s;
        return s;
      }
    }
    /**
     * <code>string hashVal = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHashValBytes() {
      java.lang.Object ref = hashVal_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hashVal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOSTPORT_FIELD_NUMBER = 2;
    private volatile java.lang.Object hostPort_;
    /**
     * <code>string hostPort = 2;</code>
     */
    public java.lang.String getHostPort() {
      java.lang.Object ref = hostPort_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostPort_ = s;
        return s;
      }
    }
    /**
     * <code>string hostPort = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostPortBytes() {
      java.lang.Object ref = hostPort_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostPort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHashValBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hashVal_);
      }
      if (!getHostPortBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hostPort_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHashValBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hashVal_);
      }
      if (!getHostPortBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hostPort_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.StorageMessages.NodeHash)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.StorageMessages.NodeHash other = (edu.usfca.cs.dfs.StorageMessages.NodeHash) obj;

      boolean result = true;
      result = result && getHashVal()
          .equals(other.getHashVal());
      result = result && getHostPort()
          .equals(other.getHostPort());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HASHVAL_FIELD_NUMBER;
      hash = (53 * hash) + getHashVal().hashCode();
      hash = (37 * hash) + HOSTPORT_FIELD_NUMBER;
      hash = (53 * hash) + getHostPort().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.StorageMessages.NodeHash parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.NodeHash parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.NodeHash parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.NodeHash parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.NodeHash parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.NodeHash parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.NodeHash parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.NodeHash parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.NodeHash parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.NodeHash parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.NodeHash parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.NodeHash parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.StorageMessages.NodeHash prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NodeHash}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NodeHash)
        edu.usfca.cs.dfs.StorageMessages.NodeHashOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_NodeHash_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_NodeHash_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.StorageMessages.NodeHash.class, edu.usfca.cs.dfs.StorageMessages.NodeHash.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.StorageMessages.NodeHash.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hashVal_ = "";

        hostPort_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_NodeHash_descriptor;
      }

      public edu.usfca.cs.dfs.StorageMessages.NodeHash getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.StorageMessages.NodeHash.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.StorageMessages.NodeHash build() {
        edu.usfca.cs.dfs.StorageMessages.NodeHash result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.StorageMessages.NodeHash buildPartial() {
        edu.usfca.cs.dfs.StorageMessages.NodeHash result = new edu.usfca.cs.dfs.StorageMessages.NodeHash(this);
        result.hashVal_ = hashVal_;
        result.hostPort_ = hostPort_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.StorageMessages.NodeHash) {
          return mergeFrom((edu.usfca.cs.dfs.StorageMessages.NodeHash)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.StorageMessages.NodeHash other) {
        if (other == edu.usfca.cs.dfs.StorageMessages.NodeHash.getDefaultInstance()) return this;
        if (!other.getHashVal().isEmpty()) {
          hashVal_ = other.hashVal_;
          onChanged();
        }
        if (!other.getHostPort().isEmpty()) {
          hostPort_ = other.hostPort_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.StorageMessages.NodeHash parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.StorageMessages.NodeHash) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object hashVal_ = "";
      /**
       * <code>string hashVal = 1;</code>
       */
      public java.lang.String getHashVal() {
        java.lang.Object ref = hashVal_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hashVal_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hashVal = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHashValBytes() {
        java.lang.Object ref = hashVal_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hashVal_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hashVal = 1;</code>
       */
      public Builder setHashVal(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hashVal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hashVal = 1;</code>
       */
      public Builder clearHashVal() {
        
        hashVal_ = getDefaultInstance().getHashVal();
        onChanged();
        return this;
      }
      /**
       * <code>string hashVal = 1;</code>
       */
      public Builder setHashValBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hashVal_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hostPort_ = "";
      /**
       * <code>string hostPort = 2;</code>
       */
      public java.lang.String getHostPort() {
        java.lang.Object ref = hostPort_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hostPort_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hostPort = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostPortBytes() {
        java.lang.Object ref = hostPort_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostPort_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hostPort = 2;</code>
       */
      public Builder setHostPort(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hostPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hostPort = 2;</code>
       */
      public Builder clearHostPort() {
        
        hostPort_ = getDefaultInstance().getHostPort();
        onChanged();
        return this;
      }
      /**
       * <code>string hostPort = 2;</code>
       */
      public Builder setHostPortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hostPort_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:NodeHash)
    }

    // @@protoc_insertion_point(class_scope:NodeHash)
    private static final edu.usfca.cs.dfs.StorageMessages.NodeHash DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.StorageMessages.NodeHash();
    }

    public static edu.usfca.cs.dfs.StorageMessages.NodeHash getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeHash>
        PARSER = new com.google.protobuf.AbstractParser<NodeHash>() {
      public NodeHash parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NodeHash(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NodeHash> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeHash> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.StorageMessages.NodeHash getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeHash_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeHash_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026storage_messages.proto\"\221\002\n\nDataPacket\022" +
      "$\n\004type\030\001 \001(\0162\026.DataPacket.packetType\022\020\n" +
      "\010fileName\030\002 \001(\t\022\020\n\010numChunk\030\003 \001(\005\022\017\n\007chu" +
      "nkId\030\004 \001(\005\022\014\n\004data\030\005 \001(\014\022\017\n\007is_last\030\006 \001(" +
      "\010\022\r\n\005usage\030\007 \001(\005\022\022\n\nrequestNum\030\010 \001(\005\022\033\n\010" +
      "nodeList\030\t \003(\0132\t.NodeHash\"I\n\npacketType\022" +
      "\013\n\007REQUEST\020\000\022\007\n\003ACK\020\001\022\010\n\004DATA\020\002\022\r\n\tHEART" +
      "BEAT\020\003\022\014\n\010NODELIST\020\004\"-\n\010NodeHash\022\017\n\007hash" +
      "Val\030\001 \001(\t\022\020\n\010hostPort\030\002 \001(\tB\022\n\020edu.usfca" +
      ".cs.dfsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DataPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DataPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataPacket_descriptor,
        new java.lang.String[] { "Type", "FileName", "NumChunk", "ChunkId", "Data", "IsLast", "Usage", "RequestNum", "NodeList", });
    internal_static_NodeHash_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NodeHash_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeHash_descriptor,
        new java.lang.String[] { "HashVal", "HostPort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
